{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gpp-burgerportaal.fullname" . }}
  labels:
    {{- include "gpp-burgerportaal.labels" . | nindent 4 }}
stringData:
  ODRC_API_KEY: {{ .Values.settings.gppPublicatiebank.apiKey | toString |  quote }}
{{- end }}
